### PR TITLE
Add NTLMv2 Support

### PR DESCRIPTION
**Pull request by jborean93**
* Changed dependency of python-ntlm3 to ntlm-auth to support NTLMv2 authentication and the various features brought on by that. Fixed up test cases now we are using a newer version of NTLM. Added appveyor and travis-ci functionality for better testing

* Bumped ntlm-auth dependency for python 2.6 changes. Added background jobs to start the flask instance for both travis and appveyor

* Added support for both appveyor and travis-ci for automated testing making it simpler to see if there are any changes

* Added support for coverall.io for coverage information.

* Added more tests to cover more code and expectations of the code.

### CODE REVIEW

**Comment by jborean93** [comment]
The main reason for this pull request is to change the python-ntlm3 dependency to another library that has more features supported such as NTLMv2 authentication, Channel Binding Tokens support and signing and sealing. The replacement dependency ntlm-auth is based on python-ntlm3 but with some major changes to take advantage of those new features.

I tried going through the normal route of updating python-ntlm3 but so far I haven't had any responses or any luck trying to get in contact with the maintainer which is why I created a new repository.

The other major change in this pull request is automated builds and coverage reports on commits and pull requests. The maintainer of requests-ntlm will have to grant permission to appveyor, travis-ci and coveralls to access this repo for it to turn on but all the hard work is done.

Once the permission has been sorted I can then update the badges to reflect the new URL's instead of my forked repo.

Happy to go through any of the other changes that you believe needs work.

Thanks

Jordan

**Comment by Lukasa** [comment]
Ok @jborean93, so before I tag in @rbcarson to help review here, we're going to need to adjust this PR a bit because it's unreviewably massive. I think you're going to need to split this into one PR for each of the above changes so that we can review them individually. Is that going to be ok for you?

**Comment by jborean93** [comment]
Hi

Happy to split it up to make it more managable, I haven't done one of these before so I am starting fresh. If we were going to split it up does this sound like a reasonable process?

1. Testing changes, I can modify the test so it covers what was there before I touched anything
2. Dependency change from python-ntlm3 with the changes for requests-ntlm

@sigmavirus24 has just gotten back to me regarding python-ntlm3 and trying to reach the maintainer again. Even if that is successful and we get the changes in there it will still require some work here to get NTLMv2 support.

Thanks

Jordan

**Comment by Lukasa** [comment]
I think we're totally willing to do some work here, that's not a problem, but we'd rather avoid changing deps if we can.

**Pull request closed without merging**
